name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4

            - name: List and Show files
              run: | 
                  echo "My"
                  ls -ltra
                  cat README.md